<?php 

return [

    [
        'id' => 'aed',
        'code_alphabetic' => 'aed',
        'code_numeric' => '784',
        'country_ids' => '["ae"]',
        'decimal_digits' => '2',
        'name' => 'United Arab Emirates Dirham',
        'name_plural' => 'UAE dirhams',
        'rounding' => '0',
        'symbol' => 'AED',
        'symbol_native' => 'د.إ.‏',
    ],

    [
        'id' => 'afn',
        'code_alphabetic' => 'afn',
        'code_numeric' => '971',
        'country_ids' => '["af"]',
        'decimal_digits' => '0',
        'name' => 'Afghan Afghani',
        'name_plural' => 'Afghan Afghanis',
        'rounding' => '0',
        'symbol' => 'Af',
        'symbol_native' => '؋',
    ],

    [
        'id' => 'all',
        'code_alphabetic' => 'all',
        'code_numeric' => '008',
        'country_ids' => '["al"]',
        'decimal_digits' => '0',
        'name' => 'Albanian Lek',
        'name_plural' => 'Albanian lekë',
        'rounding' => '0',
        'symbol' => 'ALL',
        'symbol_native' => 'Lek',
    ],

    [
        'id' => 'amd',
        'code_alphabetic' => 'amd',
        'code_numeric' => '051',
        'country_ids' => '["am"]',
        'decimal_digits' => '0',
        'name' => 'Armenian Dram',
        'name_plural' => 'Armenian drams',
        'rounding' => '0',
        'symbol' => 'AMD',
        'symbol_native' => 'դր.',
    ],

    [
        'id' => 'ars',
        'code_alphabetic' => 'ars',
        'code_numeric' => '032',
        'country_ids' => '["ar"]',
        'decimal_digits' => '2',
        'name' => 'Argentine Peso',
        'name_plural' => 'Argentine pesos',
        'rounding' => '0',
        'symbol' => 'AR$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'aud',
        'code_alphabetic' => 'aud',
        'code_numeric' => '036',
        'country_ids' => '["au","cc","cx","hm","ki","nf","nr","tv"]',
        'decimal_digits' => '2',
        'name' => 'Australian Dollar',
        'name_plural' => 'Australian dollars',
        'rounding' => '0',
        'symbol' => 'AU$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'azn',
        'code_alphabetic' => 'azn',
        'code_numeric' => '944',
        'country_ids' => '["az"]',
        'decimal_digits' => '2',
        'name' => 'Azerbaijani Manat',
        'name_plural' => 'Azerbaijani manats',
        'rounding' => '0',
        'symbol' => 'man.',
        'symbol_native' => 'ман.',
    ],

    [
        'id' => 'bam',
        'code_alphabetic' => 'bam',
        'code_numeric' => '977',
        'country_ids' => '["ba"]',
        'decimal_digits' => '2',
        'name' => 'Bosnia-Herzegovina Convertible Mark',
        'name_plural' => 'Bosnia-Herzegovina convertible marks',
        'rounding' => '0',
        'symbol' => 'KM',
        'symbol_native' => 'KM',
    ],

    [
        'id' => 'bdt',
        'code_alphabetic' => 'bdt',
        'code_numeric' => '050',
        'country_ids' => '["bd"]',
        'decimal_digits' => '2',
        'name' => 'Bangladeshi Taka',
        'name_plural' => 'Bangladeshi takas',
        'rounding' => '0',
        'symbol' => 'Tk',
        'symbol_native' => '৳',
    ],

    [
        'id' => 'bgn',
        'code_alphabetic' => 'bgn',
        'code_numeric' => '975',
        'country_ids' => '["bg"]',
        'decimal_digits' => '2',
        'name' => 'Bulgarian Lev',
        'name_plural' => 'Bulgarian leva',
        'rounding' => '0',
        'symbol' => 'BGN',
        'symbol_native' => 'лв.',
    ],

    [
        'id' => 'bhd',
        'code_alphabetic' => 'bhd',
        'code_numeric' => '048',
        'country_ids' => '["bh"]',
        'decimal_digits' => '3',
        'name' => 'Bahraini Dinar',
        'name_plural' => 'Bahraini dinars',
        'rounding' => '0',
        'symbol' => 'BD',
        'symbol_native' => 'د.ب.‏',
    ],

    [
        'id' => 'bif',
        'code_alphabetic' => 'bif',
        'code_numeric' => '108',
        'country_ids' => '["bi"]',
        'decimal_digits' => '0',
        'name' => 'Burundian Franc',
        'name_plural' => 'Burundian francs',
        'rounding' => '0',
        'symbol' => 'FBu',
        'symbol_native' => 'FBu',
    ],

    [
        'id' => 'bnd',
        'code_alphabetic' => 'bnd',
        'code_numeric' => '096',
        'country_ids' => '["bn"]',
        'decimal_digits' => '2',
        'name' => 'Brunei Dollar',
        'name_plural' => 'Brunei dollars',
        'rounding' => '0',
        'symbol' => 'BN$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'bob',
        'code_alphabetic' => 'bob',
        'code_numeric' => '068',
        'country_ids' => '["bo"]',
        'decimal_digits' => '2',
        'name' => 'Bolivian Boliviano',
        'name_plural' => 'Bolivian bolivianos',
        'rounding' => '0',
        'symbol' => 'Bs',
        'symbol_native' => 'Bs',
    ],

    [
        'id' => 'brl',
        'code_alphabetic' => 'brl',
        'code_numeric' => '986',
        'country_ids' => '["br"]',
        'decimal_digits' => '2',
        'name' => 'Brazilian Real',
        'name_plural' => 'Brazilian reals',
        'rounding' => '0',
        'symbol' => 'R$',
        'symbol_native' => 'R$',
    ],

    [
        'id' => 'bwp',
        'code_alphabetic' => 'bwp',
        'code_numeric' => '072',
        'country_ids' => '["bw","zw"]',
        'decimal_digits' => '2',
        'name' => 'Botswanan Pula',
        'name_plural' => 'Botswanan pulas',
        'rounding' => '0',
        'symbol' => 'BWP',
        'symbol_native' => 'P',
    ],

    [
        'id' => 'byn',
        'code_alphabetic' => 'byn',
        'code_numeric' => '933',
        'country_ids' => '["by"]',
        'decimal_digits' => '2',
        'name' => 'Belarusian Ruble',
        'name_plural' => 'Belarusian rubles',
        'rounding' => '0',
        'symbol' => 'Br',
        'symbol_native' => 'руб.',
    ],

    [
        'id' => 'bzd',
        'code_alphabetic' => 'bzd',
        'code_numeric' => '084',
        'country_ids' => '["bz"]',
        'decimal_digits' => '2',
        'name' => 'Belize Dollar',
        'name_plural' => 'Belize dollars',
        'rounding' => '0',
        'symbol' => 'BZ$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'cad',
        'code_alphabetic' => 'cad',
        'code_numeric' => '124',
        'country_ids' => '["ca"]',
        'decimal_digits' => '2',
        'name' => 'Canadian Dollar',
        'name_plural' => 'Canadian dollars',
        'rounding' => '0',
        'symbol' => 'CA$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'cdf',
        'code_alphabetic' => 'cdf',
        'code_numeric' => '976',
        'country_ids' => '["cd"]',
        'decimal_digits' => '2',
        'name' => 'Congolese Franc',
        'name_plural' => 'Congolese francs',
        'rounding' => '0',
        'symbol' => 'CDF',
        'symbol_native' => 'FrCD',
    ],

    [
        'id' => 'chf',
        'code_alphabetic' => 'chf',
        'code_numeric' => '756',
        'country_ids' => '["ch","li"]',
        'decimal_digits' => '2',
        'name' => 'Swiss Franc',
        'name_plural' => 'Swiss francs',
        'rounding' => '0.05',
        'symbol' => 'CHF',
        'symbol_native' => 'CHF',
    ],

    [
        'id' => 'clp',
        'code_alphabetic' => 'clp',
        'code_numeric' => '152',
        'country_ids' => '["cl"]',
        'decimal_digits' => '0',
        'name' => 'Chilean Peso',
        'name_plural' => 'Chilean pesos',
        'rounding' => '0',
        'symbol' => 'CL$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'cny',
        'code_alphabetic' => 'cny',
        'code_numeric' => '156',
        'country_ids' => '["cn"]',
        'decimal_digits' => '2',
        'name' => 'Chinese Yuan',
        'name_plural' => 'Chinese yuan',
        'rounding' => '0',
        'symbol' => 'CN¥',
        'symbol_native' => 'CN¥',
    ],

    [
        'id' => 'cop',
        'code_alphabetic' => 'cop',
        'code_numeric' => '170',
        'country_ids' => '["co"]',
        'decimal_digits' => '0',
        'name' => 'Colombian Peso',
        'name_plural' => 'Colombian pesos',
        'rounding' => '0',
        'symbol' => 'CO$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'crc',
        'code_alphabetic' => 'crc',
        'code_numeric' => '188',
        'country_ids' => '["cr"]',
        'decimal_digits' => '0',
        'name' => 'Costa Rican Colón',
        'name_plural' => 'Costa Rican colóns',
        'rounding' => '0',
        'symbol' => '₡',
        'symbol_native' => '₡',
    ],

    [
        'id' => 'cve',
        'code_alphabetic' => 'cve',
        'code_numeric' => '132',
        'country_ids' => '["cv"]',
        'decimal_digits' => '2',
        'name' => 'Cape Verdean Escudo',
        'name_plural' => 'Cape Verdean escudos',
        'rounding' => '0',
        'symbol' => 'CV$',
        'symbol_native' => 'CV$',
    ],

    [
        'id' => 'czk',
        'code_alphabetic' => 'czk',
        'code_numeric' => '203',
        'country_ids' => '["cz"]',
        'decimal_digits' => '2',
        'name' => 'Czech Republic Koruna',
        'name_plural' => 'Czech Republic korunas',
        'rounding' => '0',
        'symbol' => 'Kč',
        'symbol_native' => 'Kč',
    ],

    [
        'id' => 'djf',
        'code_alphabetic' => 'djf',
        'code_numeric' => '262',
        'country_ids' => '["dj"]',
        'decimal_digits' => '0',
        'name' => 'Djiboutian Franc',
        'name_plural' => 'Djiboutian francs',
        'rounding' => '0',
        'symbol' => 'Fdj',
        'symbol_native' => 'Fdj',
    ],

    [
        'id' => 'dkk',
        'code_alphabetic' => 'dkk',
        'code_numeric' => '208',
        'country_ids' => '["dk","fo","gl"]',
        'decimal_digits' => '2',
        'name' => 'Danish Krone',
        'name_plural' => 'Danish kroner',
        'rounding' => '0',
        'symbol' => 'Dkr',
        'symbol_native' => 'kr',
    ],

    [
        'id' => 'dop',
        'code_alphabetic' => 'dop',
        'code_numeric' => '214',
        'country_ids' => '["do"]',
        'decimal_digits' => '2',
        'name' => 'Dominican Peso',
        'name_plural' => 'Dominican pesos',
        'rounding' => '0',
        'symbol' => 'RD$',
        'symbol_native' => 'RD$',
    ],

    [
        'id' => 'dzd',
        'code_alphabetic' => 'dzd',
        'code_numeric' => '012',
        'country_ids' => '["dz"]',
        'decimal_digits' => '2',
        'name' => 'Algerian Dinar',
        'name_plural' => 'Algerian dinars',
        'rounding' => '0',
        'symbol' => 'DA',
        'symbol_native' => 'د.ج.‏',
    ],

    [
        'id' => 'egp',
        'code_alphabetic' => 'egp',
        'code_numeric' => '818',
        'country_ids' => '["eg"]',
        'decimal_digits' => '2',
        'name' => 'Egyptian Pound',
        'name_plural' => 'Egyptian pounds',
        'rounding' => '0',
        'symbol' => 'EGP',
        'symbol_native' => 'ج.م.‏',
    ],

    [
        'id' => 'ern',
        'code_alphabetic' => 'ern',
        'code_numeric' => '232',
        'country_ids' => '["er"]',
        'decimal_digits' => '2',
        'name' => 'Eritrean Nakfa',
        'name_plural' => 'Eritrean nakfas',
        'rounding' => '0',
        'symbol' => 'Nfk',
        'symbol_native' => 'Nfk',
    ],

    [
        'id' => 'etb',
        'code_alphabetic' => 'etb',
        'code_numeric' => '230',
        'country_ids' => '["et"]',
        'decimal_digits' => '2',
        'name' => 'Ethiopian Birr',
        'name_plural' => 'Ethiopian birrs',
        'rounding' => '0',
        'symbol' => 'Br',
        'symbol_native' => 'Br',
    ],

    [
        'id' => 'eur',
        'code_alphabetic' => 'eur',
        'code_numeric' => '978',
        'country_ids' => '["ad","at","ax","be","bl","cy","de","ee","es","fi","fr","gf","gp","gr","ie","it","lt","lv","lu","mc","me","mf","mq","mt","nl","pm","pt","re","si","sk","sm","tf","va","yt","zw"]',
        'decimal_digits' => '2',
        'name' => 'Euro',
        'name_plural' => 'euros',
        'rounding' => '0',
        'symbol' => '€',
        'symbol_native' => '€',
    ],

    [
        'id' => 'gbp',
        'code_alphabetic' => 'gbp',
        'code_numeric' => '826',
        'country_ids' => '["gb","gg","gs","im","io","je","zw"]',
        'decimal_digits' => '2',
        'name' => 'British Pound Sterling',
        'name_plural' => 'British pounds sterling',
        'rounding' => '0',
        'symbol' => '£',
        'symbol_native' => '£',
    ],

    [
        'id' => 'gel',
        'code_alphabetic' => 'gel',
        'code_numeric' => '981',
        'country_ids' => '["ge"]',
        'decimal_digits' => '2',
        'name' => 'Georgian Lari',
        'name_plural' => 'Georgian laris',
        'rounding' => '0',
        'symbol' => 'GEL',
        'symbol_native' => 'GEL',
    ],

    [
        'id' => 'ghs',
        'code_alphabetic' => 'ghs',
        'code_numeric' => '936',
        'country_ids' => '["gh"]',
        'decimal_digits' => '2',
        'name' => 'Ghanaian Cedi',
        'name_plural' => 'Ghanaian cedis',
        'rounding' => '0',
        'symbol' => 'GH₵',
        'symbol_native' => 'GH₵',
    ],

    [
        'id' => 'gnf',
        'code_alphabetic' => 'gnf',
        'code_numeric' => '324',
        'country_ids' => '["gn"]',
        'decimal_digits' => '0',
        'name' => 'Guinean Franc',
        'name_plural' => 'Guinean francs',
        'rounding' => '0',
        'symbol' => 'FG',
        'symbol_native' => 'FG',
    ],

    [
        'id' => 'gtq',
        'code_alphabetic' => 'gtq',
        'code_numeric' => '320',
        'country_ids' => '["gt"]',
        'decimal_digits' => '2',
        'name' => 'Guatemalan Quetzal',
        'name_plural' => 'Guatemalan quetzals',
        'rounding' => '0',
        'symbol' => 'GTQ',
        'symbol_native' => 'Q',
    ],

    [
        'id' => 'hkd',
        'code_alphabetic' => 'hkd',
        'code_numeric' => '344',
        'country_ids' => '["hk"]',
        'decimal_digits' => '2',
        'name' => 'Hong Kong Dollar',
        'name_plural' => 'Hong Kong dollars',
        'rounding' => '0',
        'symbol' => 'HK$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'hnl',
        'code_alphabetic' => 'hnl',
        'code_numeric' => '340',
        'country_ids' => '["hn"]',
        'decimal_digits' => '2',
        'name' => 'Honduran Lempira',
        'name_plural' => 'Honduran lempiras',
        'rounding' => '0',
        'symbol' => 'HNL',
        'symbol_native' => 'L',
    ],

    [
        'id' => 'hrk',
        'code_alphabetic' => 'hrk',
        'code_numeric' => '191',
        'country_ids' => '["hr"]',
        'decimal_digits' => '2',
        'name' => 'Croatian Kuna',
        'name_plural' => 'Croatian kunas',
        'rounding' => '0',
        'symbol' => 'kn',
        'symbol_native' => 'kn',
    ],

    [
        'id' => 'huf',
        'code_alphabetic' => 'huf',
        'code_numeric' => '348',
        'country_ids' => '["hu"]',
        'decimal_digits' => '0',
        'name' => 'Hungarian Forint',
        'name_plural' => 'Hungarian forints',
        'rounding' => '0',
        'symbol' => 'Ft',
        'symbol_native' => 'Ft',
    ],

    [
        'id' => 'idr',
        'code_alphabetic' => 'idr',
        'code_numeric' => '360',
        'country_ids' => '["id"]',
        'decimal_digits' => '0',
        'name' => 'Indonesian Rupiah',
        'name_plural' => 'Indonesian rupiahs',
        'rounding' => '0',
        'symbol' => 'Rp',
        'symbol_native' => 'Rp',
    ],

    [
        'id' => 'ils',
        'code_alphabetic' => 'ils',
        'code_numeric' => '376',
        'country_ids' => '["il","ps"]',
        'decimal_digits' => '2',
        'name' => 'Israeli New Sheqel',
        'name_plural' => 'Israeli new sheqels',
        'rounding' => '0',
        'symbol' => '₪',
        'symbol_native' => '₪',
    ],

    [
        'id' => 'inr',
        'code_alphabetic' => 'inr',
        'code_numeric' => '356',
        'country_ids' => '["in"]',
        'decimal_digits' => '2',
        'name' => 'Indian Rupee',
        'name_plural' => 'Indian rupees',
        'rounding' => '0',
        'symbol' => 'Rs',
        'symbol_native' => 'টকা',
    ],

    [
        'id' => 'iqd',
        'code_alphabetic' => 'iqd',
        'code_numeric' => '368',
        'country_ids' => '["iq"]',
        'decimal_digits' => '0',
        'name' => 'Iraqi Dinar',
        'name_plural' => 'Iraqi dinars',
        'rounding' => '0',
        'symbol' => 'IQD',
        'symbol_native' => 'د.ع.‏',
    ],

    [
        'id' => 'irr',
        'code_alphabetic' => 'irr',
        'code_numeric' => '364',
        'country_ids' => '["ir"]',
        'decimal_digits' => '0',
        'name' => 'Iranian Rial',
        'name_plural' => 'Iranian rials',
        'rounding' => '0',
        'symbol' => 'IRR',
        'symbol_native' => '﷼',
    ],

    [
        'id' => 'isk',
        'code_alphabetic' => 'isk',
        'code_numeric' => '352',
        'country_ids' => '["is"]',
        'decimal_digits' => '0',
        'name' => 'Icelandic Króna',
        'name_plural' => 'Icelandic krónur',
        'rounding' => '0',
        'symbol' => 'Ikr',
        'symbol_native' => 'kr',
    ],

    [
        'id' => 'jmd',
        'code_alphabetic' => 'jmd',
        'code_numeric' => '388',
        'country_ids' => '["jm"]',
        'decimal_digits' => '2',
        'name' => 'Jamaican Dollar',
        'name_plural' => 'Jamaican dollars',
        'rounding' => '0',
        'symbol' => 'J$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'jod',
        'code_alphabetic' => 'jod',
        'code_numeric' => '400',
        'country_ids' => '["jo"]',
        'decimal_digits' => '3',
        'name' => 'Jordanian Dinar',
        'name_plural' => 'Jordanian dinars',
        'rounding' => '0',
        'symbol' => 'JD',
        'symbol_native' => 'د.أ.‏',
    ],

    [
        'id' => 'jpy',
        'code_alphabetic' => 'jpy',
        'code_numeric' => '392',
        'country_ids' => '["jp"]',
        'decimal_digits' => '0',
        'name' => 'Japanese Yen',
        'name_plural' => 'Japanese yen',
        'rounding' => '0',
        'symbol' => '¥',
        'symbol_native' => '￥',
    ],

    [
        'id' => 'kes',
        'code_alphabetic' => 'kes',
        'code_numeric' => '404',
        'country_ids' => '["ke"]',
        'decimal_digits' => '2',
        'name' => 'Kenyan Shilling',
        'name_plural' => 'Kenyan shillings',
        'rounding' => '0',
        'symbol' => 'Ksh',
        'symbol_native' => 'Ksh',
    ],

    [
        'id' => 'khr',
        'code_alphabetic' => 'khr',
        'code_numeric' => '116',
        'country_ids' => '["kh"]',
        'decimal_digits' => '2',
        'name' => 'Cambodian Riel',
        'name_plural' => 'Cambodian riels',
        'rounding' => '0',
        'symbol' => 'KHR',
        'symbol_native' => '៛',
    ],

    [
        'id' => 'kmf',
        'code_alphabetic' => 'kmf',
        'code_numeric' => '174',
        'country_ids' => '["km"]',
        'decimal_digits' => '0',
        'name' => 'Comorian Franc',
        'name_plural' => 'Comorian francs',
        'rounding' => '0',
        'symbol' => 'CF',
        'symbol_native' => 'FC',
    ],

    [
        'id' => 'krw',
        'code_alphabetic' => 'krw',
        'code_numeric' => '410',
        'country_ids' => '["kr"]',
        'decimal_digits' => '0',
        'name' => 'South Korean Won',
        'name_plural' => 'South Korean won',
        'rounding' => '0',
        'symbol' => '₩',
        'symbol_native' => '₩',
    ],

    [
        'id' => 'kwd',
        'code_alphabetic' => 'kwd',
        'code_numeric' => '414',
        'country_ids' => '["kw"]',
        'decimal_digits' => '3',
        'name' => 'Kuwaiti Dinar',
        'name_plural' => 'Kuwaiti dinars',
        'rounding' => '0',
        'symbol' => 'KD',
        'symbol_native' => 'د.ك.‏',
    ],

    [
        'id' => 'kzt',
        'code_alphabetic' => 'kzt',
        'code_numeric' => '398',
        'country_ids' => '["kz"]',
        'decimal_digits' => '2',
        'name' => 'Kazakhstani Tenge',
        'name_plural' => 'Kazakhstani tenges',
        'rounding' => '0',
        'symbol' => 'KZT',
        'symbol_native' => 'тңг.',
    ],

    [
        'id' => 'lbp',
        'code_alphabetic' => 'lbp',
        'code_numeric' => '422',
        'country_ids' => '["lb"]',
        'decimal_digits' => '0',
        'name' => 'Lebanese Pound',
        'name_plural' => 'Lebanese pounds',
        'rounding' => '0',
        'symbol' => 'LB£',
        'symbol_native' => 'ل.ل.‏',
    ],

    [
        'id' => 'lkr',
        'code_alphabetic' => 'lkr',
        'code_numeric' => '144',
        'country_ids' => '["lk"]',
        'decimal_digits' => '2',
        'name' => 'Sri Lankan Rupee',
        'name_plural' => 'Sri Lankan rupees',
        'rounding' => '0',
        'symbol' => 'SLRs',
        'symbol_native' => 'SL Re',
    ],

    [
        'id' => 'lvl',
        'code_alphabetic' => 'lvl',
        'code_numeric' => '428',
        'country_ids' => '["lv"]',
        'decimal_digits' => '2',
        'name' => 'Latvian Lats',
        'name_plural' => 'Latvian lati',
        'rounding' => '0',
        'symbol' => 'Ls',
        'symbol_native' => 'Ls',
    ],

    [
        'id' => 'lyd',
        'code_alphabetic' => 'lyd',
        'code_numeric' => '434',
        'country_ids' => '["ly"]',
        'decimal_digits' => '3',
        'name' => 'Libyan Dinar',
        'name_plural' => 'Libyan dinars',
        'rounding' => '0',
        'symbol' => 'LD',
        'symbol_native' => 'د.ل.‏',
    ],

    [
        'id' => 'mad',
        'code_alphabetic' => 'mad',
        'code_numeric' => '504',
        'country_ids' => '["eh","ma"]',
        'decimal_digits' => '2',
        'name' => 'Moroccan Dirham',
        'name_plural' => 'Moroccan dirhams',
        'rounding' => '0',
        'symbol' => 'MAD',
        'symbol_native' => 'د.م.‏',
    ],

    [
        'id' => 'mdl',
        'code_alphabetic' => 'mdl',
        'code_numeric' => '498',
        'country_ids' => '["md"]',
        'decimal_digits' => '2',
        'name' => 'Moldovan Leu',
        'name_plural' => 'Moldovan lei',
        'rounding' => '0',
        'symbol' => 'MDL',
        'symbol_native' => 'MDL',
    ],

    [
        'id' => 'mga',
        'code_alphabetic' => 'mga',
        'code_numeric' => '969',
        'country_ids' => '["mg"]',
        'decimal_digits' => '0',
        'name' => 'Malagasy Ariary',
        'name_plural' => 'Malagasy Ariaries',
        'rounding' => '0',
        'symbol' => 'MGA',
        'symbol_native' => 'MGA',
    ],

    [
        'id' => 'mkd',
        'code_alphabetic' => 'mkd',
        'code_numeric' => '807',
        'country_ids' => '["mk"]',
        'decimal_digits' => '2',
        'name' => 'Macedonian Denar',
        'name_plural' => 'Macedonian denari',
        'rounding' => '0',
        'symbol' => 'MKD',
        'symbol_native' => 'MKD',
    ],

    [
        'id' => 'mmk',
        'code_alphabetic' => 'mmk',
        'code_numeric' => '104',
        'country_ids' => '["mm"]',
        'decimal_digits' => '0',
        'name' => 'Myanma Kyat',
        'name_plural' => 'Myanma kyats',
        'rounding' => '0',
        'symbol' => 'MMK',
        'symbol_native' => 'K',
    ],

    [
        'id' => 'mop',
        'code_alphabetic' => 'mop',
        'code_numeric' => '446',
        'country_ids' => '["mo"]',
        'decimal_digits' => '2',
        'name' => 'Macanese Pataca',
        'name_plural' => 'Macanese patacas',
        'rounding' => '0',
        'symbol' => 'MOP$',
        'symbol_native' => 'MOP$',
    ],

    [
        'id' => 'mur',
        'code_alphabetic' => 'mur',
        'code_numeric' => '480',
        'country_ids' => '["mu"]',
        'decimal_digits' => '0',
        'name' => 'Mauritian Rupee',
        'name_plural' => 'Mauritian rupees',
        'rounding' => '0',
        'symbol' => 'MURs',
        'symbol_native' => 'MURs',
    ],

    [
        'id' => 'mxn',
        'code_alphabetic' => 'mxn',
        'code_numeric' => '484',
        'country_ids' => '["mx"]',
        'decimal_digits' => '2',
        'name' => 'Mexican Peso',
        'name_plural' => 'Mexican pesos',
        'rounding' => '0',
        'symbol' => 'MX$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'myr',
        'code_alphabetic' => 'myr',
        'code_numeric' => '458',
        'country_ids' => '["my"]',
        'decimal_digits' => '2',
        'name' => 'Malaysian Ringgit',
        'name_plural' => 'Malaysian ringgits',
        'rounding' => '0',
        'symbol' => 'RM',
        'symbol_native' => 'RM',
    ],

    [
        'id' => 'mzn',
        'code_alphabetic' => 'mzn',
        'code_numeric' => '943',
        'country_ids' => '["mz"]',
        'decimal_digits' => '2',
        'name' => 'Mozambican Metical',
        'name_plural' => 'Mozambican meticals',
        'rounding' => '0',
        'symbol' => 'MTn',
        'symbol_native' => 'MTn',
    ],

    [
        'id' => 'nad',
        'code_alphabetic' => 'nad',
        'code_numeric' => '516',
        'country_ids' => '["na"]',
        'decimal_digits' => '2',
        'name' => 'Namibian Dollar',
        'name_plural' => 'Namibian dollars',
        'rounding' => '0',
        'symbol' => 'N$',
        'symbol_native' => 'N$',
    ],

    [
        'id' => 'ngn',
        'code_alphabetic' => 'ngn',
        'code_numeric' => '566',
        'country_ids' => '["ng"]',
        'decimal_digits' => '2',
        'name' => 'Nigerian Naira',
        'name_plural' => 'Nigerian nairas',
        'rounding' => '0',
        'symbol' => '₦',
        'symbol_native' => '₦',
    ],

    [
        'id' => 'nio',
        'code_alphabetic' => 'nio',
        'code_numeric' => '558',
        'country_ids' => '["ni"]',
        'decimal_digits' => '2',
        'name' => 'Nicaraguan Córdoba',
        'name_plural' => 'Nicaraguan córdobas',
        'rounding' => '0',
        'symbol' => 'C$',
        'symbol_native' => 'C$',
    ],

    [
        'id' => 'nok',
        'code_alphabetic' => 'nok',
        'code_numeric' => '578',
        'country_ids' => '["aq","bv","no","sj"]',
        'decimal_digits' => '2',
        'name' => 'Norwegian Krone',
        'name_plural' => 'Norwegian kroner',
        'rounding' => '0',
        'symbol' => 'Nkr',
        'symbol_native' => 'kr',
    ],

    [
        'id' => 'npr',
        'code_alphabetic' => 'npr',
        'code_numeric' => '524',
        'country_ids' => '["np"]',
        'decimal_digits' => '2',
        'name' => 'Nepalese Rupee',
        'name_plural' => 'Nepalese rupees',
        'rounding' => '0',
        'symbol' => 'NPRs',
        'symbol_native' => 'नेरू',
    ],

    [
        'id' => 'nzd',
        'code_alphabetic' => 'nzd',
        'code_numeric' => '554',
        'country_ids' => '["ck","nu","nz","pn","tk"]',
        'decimal_digits' => '2',
        'name' => 'New Zealand Dollar',
        'name_plural' => 'New Zealand dollars',
        'rounding' => '0',
        'symbol' => 'NZ$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'omr',
        'code_alphabetic' => 'omr',
        'code_numeric' => '512',
        'country_ids' => '["om"]',
        'decimal_digits' => '3',
        'name' => 'Omani Rial',
        'name_plural' => 'Omani rials',
        'rounding' => '0',
        'symbol' => 'OMR',
        'symbol_native' => 'ر.ع.‏',
    ],

    [
        'id' => 'pab',
        'code_alphabetic' => 'pab',
        'code_numeric' => '590',
        'country_ids' => '["pa"]',
        'decimal_digits' => '2',
        'name' => 'Panamanian Balboa',
        'name_plural' => 'Panamanian balboas',
        'rounding' => '0',
        'symbol' => 'B/.',
        'symbol_native' => 'B/.',
    ],

    [
        'id' => 'pen',
        'code_alphabetic' => 'pen',
        'code_numeric' => '604',
        'country_ids' => '["pe"]',
        'decimal_digits' => '2',
        'name' => 'Peruvian Nuevo Sol',
        'name_plural' => 'Peruvian nuevos soles',
        'rounding' => '0',
        'symbol' => 'S/.',
        'symbol_native' => 'S/.',
    ],

    [
        'id' => 'php',
        'code_alphabetic' => 'php',
        'code_numeric' => '608',
        'country_ids' => '["ph"]',
        'decimal_digits' => '2',
        'name' => 'Philippine Peso',
        'name_plural' => 'Philippine pesos',
        'rounding' => '0',
        'symbol' => '₱',
        'symbol_native' => '₱',
    ],

    [
        'id' => 'pkr',
        'code_alphabetic' => 'pkr',
        'code_numeric' => '586',
        'country_ids' => '["pk"]',
        'decimal_digits' => '0',
        'name' => 'Pakistani Rupee',
        'name_plural' => 'Pakistani rupees',
        'rounding' => '0',
        'symbol' => 'PKRs',
        'symbol_native' => '₨',
    ],

    [
        'id' => 'pln',
        'code_alphabetic' => 'pln',
        'code_numeric' => '985',
        'country_ids' => '["pl"]',
        'decimal_digits' => '2',
        'name' => 'Polish Zloty',
        'name_plural' => 'Polish zlotys',
        'rounding' => '0',
        'symbol' => 'zł',
        'symbol_native' => 'zł',
    ],

    [
        'id' => 'pyg',
        'code_alphabetic' => 'pyg',
        'code_numeric' => '600',
        'country_ids' => '["py"]',
        'decimal_digits' => '0',
        'name' => 'Paraguayan Guarani',
        'name_plural' => 'Paraguayan guaranis',
        'rounding' => '0',
        'symbol' => '₲',
        'symbol_native' => '₲',
    ],

    [
        'id' => 'qar',
        'code_alphabetic' => 'qar',
        'code_numeric' => '634',
        'country_ids' => '["qa"]',
        'decimal_digits' => '2',
        'name' => 'Qatari Rial',
        'name_plural' => 'Qatari rials',
        'rounding' => '0',
        'symbol' => 'QR',
        'symbol_native' => 'ر.ق.‏',
    ],

    [
        'id' => 'ron',
        'code_alphabetic' => 'ron',
        'code_numeric' => '946',
        'country_ids' => '["ro"]',
        'decimal_digits' => '2',
        'name' => 'Romanian Leu',
        'name_plural' => 'Romanian lei',
        'rounding' => '0',
        'symbol' => 'RON',
        'symbol_native' => 'RON',
    ],

    [
        'id' => 'rsd',
        'code_alphabetic' => 'rsd',
        'code_numeric' => '941',
        'country_ids' => '["rs"]',
        'decimal_digits' => '0',
        'name' => 'Serbian Dinar',
        'name_plural' => 'Serbian dinars',
        'rounding' => '0',
        'symbol' => 'din.',
        'symbol_native' => 'дин.',
    ],

    [
        'id' => 'rub',
        'code_alphabetic' => 'rub',
        'code_numeric' => '643',
        'country_ids' => '["ru"]',
        'decimal_digits' => '2',
        'name' => 'Russian Ruble',
        'name_plural' => 'Russian rubles',
        'rounding' => '0',
        'symbol' => 'RUB',
        'symbol_native' => '₽.',
    ],

    [
        'id' => 'rwf',
        'code_alphabetic' => 'rwf',
        'code_numeric' => '646',
        'country_ids' => '["rw"]',
        'decimal_digits' => '0',
        'name' => 'Rwandan Franc',
        'name_plural' => 'Rwandan francs',
        'rounding' => '0',
        'symbol' => 'RWF',
        'symbol_native' => 'FR',
    ],

    [
        'id' => 'sar',
        'code_alphabetic' => 'sar',
        'code_numeric' => '682',
        'country_ids' => '["sa"]',
        'decimal_digits' => '2',
        'name' => 'Saudi Riyal',
        'name_plural' => 'Saudi riyals',
        'rounding' => '0',
        'symbol' => 'SR',
        'symbol_native' => 'ر.س.‏',
    ],

    [
        'id' => 'sdg',
        'code_alphabetic' => 'sdg',
        'code_numeric' => '938',
        'country_ids' => '["sd"]',
        'decimal_digits' => '2',
        'name' => 'Sudanese Pound',
        'name_plural' => 'Sudanese pounds',
        'rounding' => '0',
        'symbol' => 'SDG',
        'symbol_native' => 'SDG',
    ],

    [
        'id' => 'sek',
        'code_alphabetic' => 'sek',
        'code_numeric' => '752',
        'country_ids' => '["se"]',
        'decimal_digits' => '2',
        'name' => 'Swedish Krona',
        'name_plural' => 'Swedish kronor',
        'rounding' => '0',
        'symbol' => 'Skr',
        'symbol_native' => 'kr',
    ],

    [
        'id' => 'sgd',
        'code_alphabetic' => 'sgd',
        'code_numeric' => '702',
        'country_ids' => '["bn","sg"]',
        'decimal_digits' => '2',
        'name' => 'Singapore Dollar',
        'name_plural' => 'Singapore dollars',
        'rounding' => '0',
        'symbol' => 'S$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'sos',
        'code_alphabetic' => 'sos',
        'code_numeric' => '706',
        'country_ids' => '["so"]',
        'decimal_digits' => '0',
        'name' => 'Somali Shilling',
        'name_plural' => 'Somali shillings',
        'rounding' => '0',
        'symbol' => 'Ssh',
        'symbol_native' => 'Ssh',
    ],

    [
        'id' => 'syp',
        'code_alphabetic' => 'syp',
        'code_numeric' => '760',
        'country_ids' => '["sy"]',
        'decimal_digits' => '0',
        'name' => 'Syrian Pound',
        'name_plural' => 'Syrian pounds',
        'rounding' => '0',
        'symbol' => 'SY£',
        'symbol_native' => 'ل.س.‏',
    ],

    [
        'id' => 'thb',
        'code_alphabetic' => 'thb',
        'code_numeric' => '764',
        'country_ids' => '["th"]',
        'decimal_digits' => '2',
        'name' => 'Thai Baht',
        'name_plural' => 'Thai baht',
        'rounding' => '0',
        'symbol' => '฿',
        'symbol_native' => '฿',
    ],

    [
        'id' => 'tnd',
        'code_alphabetic' => 'tnd',
        'code_numeric' => '788',
        'country_ids' => '["tn"]',
        'decimal_digits' => '3',
        'name' => 'Tunisian Dinar',
        'name_plural' => 'Tunisian dinars',
        'rounding' => '0',
        'symbol' => 'DT',
        'symbol_native' => 'د.ت.‏',
    ],

    [
        'id' => 'top',
        'code_alphabetic' => 'top',
        'code_numeric' => '776',
        'country_ids' => '["to"]',
        'decimal_digits' => '2',
        'name' => 'Tongan Paʻanga',
        'name_plural' => 'Tongan paʻanga',
        'rounding' => '0',
        'symbol' => 'T$',
        'symbol_native' => 'T$',
    ],

    [
        'id' => 'try',
        'code_alphabetic' => 'try',
        'code_numeric' => '949',
        'country_ids' => '["tr"]',
        'decimal_digits' => '2',
        'name' => 'Turkish Lira',
        'name_plural' => 'Turkish Lira',
        'rounding' => '0',
        'symbol' => 'TL',
        'symbol_native' => 'TL',
    ],

    [
        'id' => 'ttd',
        'code_alphabetic' => 'ttd',
        'code_numeric' => '780',
        'country_ids' => '["tt"]',
        'decimal_digits' => '2',
        'name' => 'Trinidad and Tobago Dollar',
        'name_plural' => 'Trinidad and Tobago dollars',
        'rounding' => '0',
        'symbol' => 'TT$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'twd',
        'code_alphabetic' => 'twd',
        'code_numeric' => '901',
        'country_ids' => '["tw"]',
        'decimal_digits' => '2',
        'name' => 'New Taiwan Dollar',
        'name_plural' => 'New Taiwan dollars',
        'rounding' => '0',
        'symbol' => 'NT$',
        'symbol_native' => 'NT$',
    ],

    [
        'id' => 'tzs',
        'code_alphabetic' => 'tzs',
        'code_numeric' => '834',
        'country_ids' => '["tz"]',
        'decimal_digits' => '0',
        'name' => 'Tanzanian Shilling',
        'name_plural' => 'Tanzanian shillings',
        'rounding' => '0',
        'symbol' => 'TSh',
        'symbol_native' => 'TSh',
    ],

    [
        'id' => 'uah',
        'code_alphabetic' => 'uah',
        'code_numeric' => '980',
        'country_ids' => '["ua"]',
        'decimal_digits' => '2',
        'name' => 'Ukrainian Hryvnia',
        'name_plural' => 'Ukrainian hryvnias',
        'rounding' => '0',
        'symbol' => '₴',
        'symbol_native' => '₴',
    ],

    [
        'id' => 'ugx',
        'code_alphabetic' => 'ugx',
        'code_numeric' => '800',
        'country_ids' => '["ug"]',
        'decimal_digits' => '0',
        'name' => 'Ugandan Shilling',
        'name_plural' => 'Ugandan shillings',
        'rounding' => '0',
        'symbol' => 'USh',
        'symbol_native' => 'USh',
    ],

    [
        'id' => 'usd',
        'code_alphabetic' => 'usd',
        'code_numeric' => '840',
        'country_ids' => '["as","bq","ec","fm","gu","mf","mh","mp","pr","pw","sv","tc","tl","um","us","vg","vi","zw"]',
        'decimal_digits' => '2',
        'name' => 'US Dollar',
        'name_plural' => 'US dollars',
        'rounding' => '0',
        'symbol' => '$',
        'symbol_native' => '$',
    ],

    [
        'id' => 'uyu',
        'code_alphabetic' => 'uyu',
        'code_numeric' => '858',
        'country_ids' => '["uy"]',
        'decimal_digits' => '2',
        'name' => 'Uruguayan Peso',
        'name_plural' => 'Uruguayan pesos',
        'rounding' => '0',
        'symbol' => '$U',
        'symbol_native' => '$',
    ],

    [
        'id' => 'uzs',
        'code_alphabetic' => 'uzs',
        'code_numeric' => '860',
        'country_ids' => '["uz"]',
        'decimal_digits' => '0',
        'name' => 'Uzbekistan Som',
        'name_plural' => 'Uzbekistan som',
        'rounding' => '0',
        'symbol' => 'UZS',
        'symbol_native' => 'UZS',
    ],

    [
        'id' => 'vnd',
        'code_alphabetic' => 'vnd',
        'code_numeric' => '704',
        'country_ids' => '["vn"]',
        'decimal_digits' => '0',
        'name' => 'Vietnamese Dong',
        'name_plural' => 'Vietnamese dong',
        'rounding' => '0',
        'symbol' => '₫',
        'symbol_native' => '₫',
    ],

    [
        'id' => 'xaf',
        'code_alphabetic' => 'xaf',
        'code_numeric' => '950',
        'country_ids' => '["cf","cg","cm","ga","gq","td"]',
        'decimal_digits' => '0',
        'name' => 'CFA Franc BEAC',
        'name_plural' => 'CFA francs BEAC',
        'rounding' => '0',
        'symbol' => 'FCFA',
        'symbol_native' => 'FCFA',
    ],

    [
        'id' => 'xof',
        'code_alphabetic' => 'xof',
        'code_numeric' => '952',
        'country_ids' => '["bj","bf","ci","gw","ml","ne","sn","tg"]',
        'decimal_digits' => '0',
        'name' => 'CFA Franc BCEAO',
        'name_plural' => 'CFA francs BCEAO',
        'rounding' => '0',
        'symbol' => 'CFA',
        'symbol_native' => 'CFA',
    ],

    [
        'id' => 'yer',
        'code_alphabetic' => 'yer',
        'code_numeric' => '886',
        'country_ids' => '["ye"]',
        'decimal_digits' => '0',
        'name' => 'Yemeni Rial',
        'name_plural' => 'Yemeni rials',
        'rounding' => '0',
        'symbol' => 'YR',
        'symbol_native' => 'ر.ي.‏',
    ],

    [
        'id' => 'zar',
        'code_alphabetic' => 'zar',
        'code_numeric' => '710',
        'country_ids' => '["na","ls","sz","za","zw"]',
        'decimal_digits' => '2',
        'name' => 'South African Rand',
        'name_plural' => 'South African rand',
        'rounding' => '0',
        'symbol' => 'R',
        'symbol_native' => 'R',
    ],

];