name: monorepo-validate

on:
    push:
    pull_request:

permissions:
    contents: read

jobs:
    run-validation:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false
            - name: Cache dependencies
              uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
              with:
                  path: vendor
                  key: composer-${{ hashFiles('composer.lock') }}
            - name: Setup PHP
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
              with:
                  php-version: 8.1
                  extensions: mbstring, pdo, pdo_sqlite
                  coverage: none
            - name: Install dependencies
              run: composer install -n --prefer-dist
            - name: Validate Dependencies are consistent
              run: vendor/bin/monorepo-builder validate
