name: monorepo-validate

on:
    push:
    pull_request:

permissions:
    contents: read

jobs:
    run-validation:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
              with:
                  persist-credentials: false
            - name: Cache dependencies
              uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
              with:
                  path: vendor
                  key: composer-${{ hashFiles('composer.lock') }}
            - name: Setup PHP
              uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
              with:
                  php-version: 8.1
                  extensions: mbstring, pdo, pdo_sqlite
                  coverage: none
            - name: Install dependencies
              run: composer install -n --prefer-dist
            - name: Validate Dependencies are consistent
              run: vendor/bin/monorepo-builder validate
